// Mirrors backend/src/controllers/educationController.js STATIC_DISEASES,
// extended to cover the full list called out in the product spec.
export const FALLBACK_DISEASES = [
  { id: 'd1', disease_name: 'Malaria', icon: 'bug-outline', symptoms: 'Fever, chills, headache, fatigue', prevention: 'Use bed nets, eliminate standing water, wear repellent at dusk', climate_relation: 'Increased rainfall and temperature expand mosquito breeding areas', recommended_action: 'Seek medical care within 24 hours of fever' },
  { id: 'd2', disease_name: 'Cholera', icon: 'water-outline', symptoms: 'Watery diarrhea, vomiting, dehydration', prevention: 'Boil or treat drinking water, wash hands, safe food handling', climate_relation: 'Floods contaminate water supplies and spread the bacteria', recommended_action: 'Oral rehydration immediately and urgent medical care' },
  { id: 'd3', disease_name: 'Dengue', icon: 'bug-outline', symptoms: 'High fever, severe headache, joint and muscle pain', prevention: 'Remove mosquito breeding sites, use nets and repellent', climate_relation: 'Warmer, wetter conditions expand mosquito habitat range', recommended_action: 'Rest, fluids, and medical monitoring for warning signs' },
  { id: 'd4', disease_name: 'Typhoid', icon: 'restaurant-outline', symptoms: 'Prolonged fever, weakness, stomach pain', prevention: 'Safe water and food hygiene, vaccination where available', climate_relation: 'Flooding and poor sanitation infrastructure spread contamination', recommended_action: 'See a clinician for antibiotic treatment' },
  { id: 'd5', disease_name: 'Heat Stroke', icon: 'thermometer-outline', symptoms: 'High body temperature, confusion, hot dry skin', prevention: 'Stay hydrated, avoid midday sun, wear light clothing', climate_relation: 'Extreme heat events are increasing across northern regions', recommended_action: 'Move to shade, cool the body, call emergency services' },
  { id: 'd6', disease_name: 'Heat Exhaustion', icon: 'sunny-outline', symptoms: 'Heavy sweating, weakness, dizziness, nausea', prevention: 'Rest during peak heat, drink water regularly', climate_relation: 'Rising temperatures increase frequency in outdoor workers', recommended_action: 'Rest in a cool place and rehydrate with fluids' },
  { id: 'd7', disease_name: 'Asthma', icon: 'medkit-outline', symptoms: 'Wheezing, shortness of breath, chest tightness', prevention: 'Avoid smoke and dust, keep inhalers accessible', climate_relation: 'Air pollution and dust from droughts trigger flare-ups', recommended_action: 'Use prescribed inhaler and seek care if breathing worsens' },
  { id: 'd8', disease_name: 'Respiratory Diseases', icon: 'medkit-outline', symptoms: 'Coughing, breathing difficulty, chest pain', prevention: 'Reduce indoor smoke, wear masks in dusty conditions', climate_relation: 'Air pollution and wildfire smoke worsen respiratory health', recommended_action: 'Consult a health worker for persistent symptoms' },
  { id: 'd9', disease_name: 'Skin Infections', icon: 'body-outline', symptoms: 'Rashes, itching, redness, sores', prevention: 'Keep skin clean and dry, avoid contaminated floodwater', climate_relation: 'Flooding and humidity increase fungal and bacterial infections', recommended_action: 'Keep the area clean and seek care if it spreads' },
  { id: 'd10', disease_name: 'Dehydration', icon: 'water-outline', symptoms: 'Thirst, dry mouth, dizziness, dark urine', prevention: 'Drink water regularly, especially during heat waves', climate_relation: 'Extreme heat and water scarcity increase risk', recommended_action: 'Rehydrate with water or oral rehydration salts' },
  { id: 'd11', disease_name: 'Food Poisoning', icon: 'restaurant-outline', symptoms: 'Nausea, vomiting, stomach cramps, diarrhea', prevention: 'Store food properly, cook thoroughly, avoid spoiled food', climate_relation: 'Heat accelerates food spoilage and bacterial growth', recommended_action: 'Rehydrate and seek care if symptoms persist beyond 2 days' },
  { id: 'd12', disease_name: 'Waterborne Diseases', icon: 'water-outline', symptoms: 'Diarrhea, cramps, fever, fatigue', prevention: 'Treat drinking water, maintain sanitation', climate_relation: 'Floods and droughts both compromise safe water access', recommended_action: 'Use oral rehydration and seek medical care' },
];
