export const FALLBACK_REPORTS = [
  {
    id: 'r1',
    village: 'Ndogbong',
    subdivision: 'Douala 3',
    region: 'Littoral',
    description: 'Main access road submerged after heavy overnight rainfall; several homes affected.',
    severity: 'High',
    status: 'Verified',
    created_at: '2 days ago',
    latitude: 4.051,
    longitude: 9.768,
  },
  {
    id: 'r2',
    village: 'Biyem-Assi',
    subdivision: 'Yaoundé 6',
    region: 'Centre',
    description: 'Minor water pooling near the market, receding by midday.',
    severity: 'Low',
    status: 'Pending',
    created_at: '5 hours ago',
    latitude: 3.848,
    longitude: 11.502,
  },
  {
    id: 'r3',
    village: 'Limbe Down Beach',
    subdivision: 'Limbe 1',
    region: 'Southwest',
    description: 'Coastal flooding at high tide damaging fishing equipment along the shoreline.',
    severity: 'Critical',
    status: 'Verified',
    created_at: '1 day ago',
    latitude: 4.153,
    longitude: 9.242,
  },
];
